---
title: 'Privatization of AI research: Executing regressions'
author: "Daniel S. Hain (dsh@business.aau.dk)"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
    theme: flatly
---

```{r setup, include=FALSE}
# Knitr options
### Generic preamble
rm(list = ls())
Sys.setenv(LANG = "en") # For english language
options(scipen = 5) # To deactivate annoying scientific number notation

# rm(list=ls()); graphics.off() # get rid of everything in the workspace
if (!require("knitr")) install.packages("knitr"); library(knitr) # For display of the markdown

### Knitr options
knitr::opts_chunk$set(warning=FALSE,
                     message=FALSE,
                     fig.align="center"
                     )

library(DBI) # GEneral R database interface
library(RPostgres) # PostgreSQL interface driver
library(dbplyr) # for dplyr with databases

### Database connection

# set up connection to existing PostgreSQL database, just plug in own details
con <- dbConnect(drv = RPostgres::Postgres(), 
                 dbname = "patentdb",
                 host = "130.225.57.105", port = 5432,
                 user = "patentdbowner", password = "e6rKPT2iZ99@PKaa")
```

```{r}
### Load packages
library(tidyverse) # Collection of all the good stuff like dplyr, ggplot2 ect.
library(magrittr) # For extra-piping operators (eg. %<>%)

# Descriptives
library(skimr)
library(stargazer)

# Viz
library(patchwork)
```

# Data preperation

## Institutions

## Author 

### Author static

```{r}
tbl_author_stat <- readRDS('../../temp/tbl_author_type.rds')

## FWe only include researcher which are observed for at least five years after 2000, and exclude researcher where the latest observation was before 2015. 
tbl_author_stat %<>%
  filter(author_type %in% c('academia', 'switcher') &
           year_n >= 5 &
           year_end >= 2015) 

# Insert gender
tbl_author_stat %<>% 
  left_join(tbl(con, "author_gender") %>% select(id, full_name, gender), by = c('author_id' = 'id'), copy = TRUE) %>%
  replace_na(list(gender = 'male')) %>% # Strong assumption to get rid of NAs
  mutate(gender = ifelse(gender == 'male', TRUE, FALSE)) # Coded logical, where male = 1
```

### Author Dynamic

```{r}
tbl_author_dyn <- readRDS('../../temp/tbl_author_dyn_all.rds')

# deal with NAs
tbl_author_dyn %<>%
  replace_na(list(cent_dgr = 0, cent_dgr_ind = 0, field_of_study_id = 0, field_of_study_name = 'none', field_n = 0, dl_n = 0, dl_researcher = FALSE))
```


## Others

### Field of study

```{r}
# Define the number of fields to be included
n_fos <- 50

# Extract Fos
fos_main <- tbl_author_dyn %>% count(field_of_study_name, sort = TRUE) %>%
  slice(2:n_fos)
```

```{r}
#Update author dyn
tbl_author_dyn %<>%
  mutate(field_of_study_name = ifelse(field_of_study_name %in% (fos_main %>% pull(field_of_study_name)), field_of_study_name, 'others') %>% factor())

# GEt main FoS
author_main_fos <- tbl_author_dyn %>%
  count(author_id, field_of_study_name, sort = TRUE) %>%
  group_by(author_id) %>%
    mutate(n = ifelse(field_of_study_name == 'others', 0, n)) %>%
    arrange(author_id, desc(n)) %>%
    slice(1:1) %>%
  ungroup()

# Join with author static
tbl_author_stat %<>% 
  left_join(author_main_fos %>% select(author_id, field_of_study_name), by = 'author_id') %>%
  replace_na(list(field_of_study_name = 'others')) 
```



# Regression data prep

```{r}
# Create main data with restrictions on type
data <- tbl_author_dyn %>% 
  inner_join(tbl_author_stat %>% select(author_id, gender), by = 'author_id') %>%
  distinct(author_id, year, .keep_all = TRUE)
```

```{r}
# Create some independent variables
data %<>%
  group_by(author_id) %>%
  mutate(seniority = year - min(year, na.rm = TRUE) + 1,
         cit_n = cit_mean * paper_n,
         cit_n_cum = cit_n %>% cumsum()) %>%
  # Introduce Lags
  mutate(cit_n_cum = cit_n_cum %>% lag(1),
         cent_dgr = cent_dgr %>% lag(1),
         cent_dgr_ind = cent_dgr %>% lag(1),
         dl_researcher = dl_researcher %>% lag(1),
         field_of_study_name = field_of_study_name %>% lag(1)) %>%
  ungroup() 
```

```{r}
# Create DV
data %<>%
  # Citation rank
  group_by(year) %>%
  mutate(citation_rank_single = cit_mean %>% percent_rank()) %>%
  ungroup() %>%
  # Rolling mean
  arrange(author_id, year) %>%
  group_by(author_id) %>%
  mutate(citation_rank = citation_rank_single %>% slider::slide_dbl(~mean(.x), .before = 2)) %>%
  ungroup()
```

```{r}
# Some last preprocessing
data %<>%
  filter(year >= 2000) %>%          
  group_by(author_id) %>%
  mutate(time = 1:n()) %>%
  ungroup() %>%
  mutate(year = year %>% factor()) %>%
  drop_na() %>%
  # nicer order
  relocate(author_id, author_type, gender, year, time, switch, transited, citation_rank, cit_n_cum, paper_n) %>%
  arrange(author_id, time)
```


```{r}
data %>% saveRDS('../../temp/reg_data.rds')
```



# Suvival Analysis 

```{r}
library(survival)
library(survminer)
library(ggfortify)
```

## PReperation 

```{r}
### Prepare for regression
data_surv <- data %>% 
  # Calso lag citation rank
  #group_by(author_id) %>%
  #mutate(citation_rank = citation_rank %>% lag(1)) %>%
  #ungroup() %>%
  # other variables to try
  mutate(star = citation_rank >= 0.9)
```

```{r}
# Surf object
surv_object <- Surv(time = data_surv$time, event = data_surv$transited)
```


## Kaplan-Meier Method and Log Rank Test

```{r}
fit_km0 <- survfit(surv_object ~ 1, 
                   data = data_surv)
fit_km1 <- survfit(surv_object ~ star, 
                   data = data_surv)
fit_km2 <- survfit(surv_object ~ dl_researcher, 
                   data = data_surv)
fit_km3 <- survfit(surv_object ~ gender,
                   data = data_surv)
```

```{r}
p1 <- fit_km0 %>% autoplot() + labs(title= 'KM: baseline')
p2 <- fit_km1 %>% autoplot() + labs(title= 'KM: Star citations')
p3 <- fit_km2 %>% autoplot() + labs(title= 'KM: DL researcher')
p4 <- fit_km3 %>% autoplot() + labs(title= 'KM: Gender')

#(p1 + p2) / (p3 + p4) +  plot_layout(guides = "collect") & theme(legend.position = 'bottom') & labs(x = 'Time', y = 'Survival Probability')
```

## Cox Proportional Hazard Model

```{r}
### Fir Cox proportional hazard model

#Baseline
fit_cox0 <- coxph(surv_object ~ seniority + gender + field_of_study_name + year,
                  data = data_surv)

fit_cox1 <- coxph(surv_object ~ seniority + gender + field_of_study_name  + year + dl_researcher,
                  data = data_surv)

fit_cox2 <- coxph(surv_object ~ seniority + gender + field_of_study_name + year + cent_dgr + cent_dgr_ind,
                  data = data_surv)

fit_cox3 <- coxph(surv_object ~ seniority + gender + field_of_study_name + year + paper_n + citation_rank + log(cit_n_cum + 1) ,
                  data = data_surv)

fit_cox4 <- coxph(surv_object ~ seniority + gender + field_of_study_name + year + dl_researcher + cent_dgr + cent_dgr_ind +  paper_n + citation_rank + log(cit_n_cum + 1),
                  data = data_surv)
```


```{r}
stargazer(fit_cox0, fit_cox1, fit_cox2, fit_cox3, fit_cox4, type = 'latex', 
          omit = c( 'field_of_study_name', 'year', 'Constant'))
```

```{r}
stargazer(fit_cox0, fit_cox1, fit_cox2, fit_cox3, fit_cox4, type = 'text',
          omit = c( 'field_of_study_name', 'year', 'Constant'))
```

```{r}
fit_cox4 %>% ggforest(data = data_surv)
```



# Propensity Score matching

```{r}
library(MatchIt)
```

```{r}
set.seed(1337)
match_out<-  tbl_author_stat %>% 
  # Preselection
  select(author_id , author_type, paper_mean, cit_mean, year_n, year_end, gender, field_of_study_name) %>%
  mutate(author_type = (author_type %>% factor() %>% as.numeric()) -1 ) %>%
  # Matching
  matchit(author_type ~ paper_mean + cit_mean + year_end + gender + field_of_study_name, exact = 'year_n',
                      data = ., verbose = FALSE, method = "nearest", ratio = 1) # OR method  "genetic" ... takes forever.....
```

```{r}
# Match table for use lateron
match_data <- match_out %>% 
  match.data() %>% 
  as_tibble() %>% 
  select(author_id, distance, weights)
```

```{r}
matched_pairs  <- bind_cols( tbl_author_stat[row.names(match_out$match.matrix),"author_id"] , tbl_author_stat[match_out$match.matrix,"author_id"] ) %>%
  rename(orig_author_id = `author_id...1`,
         author_id = `author_id...2`) 
```

```{r}
# Get the time where the matched switcher transits
matched_pairs %<>%
  left_join(data %>% filter(switch == TRUE) %>% select(author_id, time) %>% distinct(author_id, .keep_all = TRUE), by = c('orig_author_id' = 'author_id')) %>%
  mutate(switch = TRUE) %>%
  drop_na() 
```


# Diff-in-Diff

## Preprocessing
```{r}
# Filter only NN matched author pairs
data_did <- data %>%
  semi_join(match_data, by = 'author_id')

# Update the corresponding transition time of university by their matched switcher
data_did %<>%
  rows_update(matched_pairs %>% select(-orig_author_id), by = c('author_id', 'time'))

# Update Transited
data_did %<>%
  mutate(transited = NA) %>%
  group_by(author_id) %>%
  mutate(transited = ifelse(lag(switch, 1) == TRUE, TRUE, transited)) %>%
  fill(transited, .direction = 'down') %>%
  replace_na(list('transited' = FALSE)) %>%
  ungroup()
```

```{r}
# Some extra variables
data_did %<>%
  group_by(author_id) %>%
  mutate(switcher = author_type == 'switcher',
         transited_t = ifelse(transited == TRUE, 1, 0)) %>%
  mutate(transited_t = transited_t %>%cumsum()) %>%
  ungroup()
```

```{r}
# Nicer ordering
data_did %<>%
  relocate(author_id, author_type, gender, year, time, switch, transited, transited_t, citation_rank, cit_n_cum, paper_n) %>%
  arrange(author_id, time)
```

```{r}
# For the interaction plot code logical to numeric
# data_did %<>%  mutate(switcher = switcher %>% as.numeric(), transited = transited %>% as.numeric())
```

```{r}
data_did %>% saveRDS('../../temp/reg_data_did.rds')
```

## Models

```{r}
# fit_did_0 <- lm(citation_rank ~ switcher + field_of_study_name, data = data_did)

fit_did_0 <- lm(citation_rank ~ (switcher + transited)^2 + field_of_study_name + year + seniority + gender + field_of_study_name
                , data = data_did)
fit_did_1 <- lm(citation_rank ~ (switcher + transited)^2 + field_of_study_name + year + seniority + gender + field_of_study_name + cent_dgr + cent_dgr_ind
                , data = data_did)
fit_did_2 <- lm(citation_rank ~ (switcher + transited)^2 + field_of_study_name + year + seniority + gender + field_of_study_name + (switcher + transited_t)^2
                , data = data_did)
fit_did_3 <- lm(citation_rank ~ (switcher + transited)^2 + field_of_study_name + year + seniority + gender + field_of_study_name + (switcher + transited_t)^2 + cent_dgr + cent_dgr_ind 
                , data = data_did)

# + paper_n ?
```

```{r}
stargazer(fit_did_0, fit_did_1, fit_did_2, fit_did_3, type = 'text',
          omit = c('field_of_study_name', 'year', 'Constant'))
```

```{r}
stargazer(fit_did_0, fit_did_1, fit_did_2, fit_did_3, type = 'text',
          omit = c('field_of_study_name', 'year', 'Constant'))
```

```{r}
stargazer(fit_did_0, fit_did_1, fit_did_2, fit_did_3, type = 'latex',
          omit = c('field_of_study_name', 'year', 'Constant'))
```


### Template new plotting model

```{r}
#library(interplot)
#fit_did_2 %>% interplot(var1 ="switcher", var2 = "transited_t", hist = TRUE) 
```

```{r}
library(interactions)
fit_did_2 %>% interact_plot(pred = transited_t, modx = switcher,
                            interval = TRUE) +
  theme(legend.position = 'bottom')

```

```{r}
ggsave('../../output/fig_interaction_1.png', width = 10, height = 7.5, units = 'cm')
```


```{r}
library(interactions)
fit_did_2 %>% interact_plot(pred = transited_t, modx = switcher,
                            interval = TRUE, linearity.check = TRUE)
```








